version: '3'
services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: admin@123!
    networks:
      - my_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    volumes:
      - ./wordpress_php:/var/www/html/wp-config.php
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: admin@123!
    ports:
      - "80:80"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "90:80"
    depends_on:
      - wordpress
    networks:
      - my_network

volumes:
  db_data:
  wordpress_php:

networks:
  my_network:

